AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

AsciiComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 250
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Max: 10

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Rails/FindEach:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

FileName:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/PercentLiteralDelimiters:
  Enabled: false
