default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: d_h_viet
  password:
  database: learn_rails
  schema_search_path: public

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

